version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: passmgr_web
    restart: always
    command: /start
    volumes:
      - .:/app
      - static_volume_pass:/pass_static
    ports:
      - 7001:7000

  nginx:
    build: ./nginx
    volumes:
      - static_volume_pass:/pass_static
    restart: always
    ports:
      - 81:81
    depends_on:
      - web

volumes:
  static_volume_pass: