version: '3.9'

services:
  web:
    build: .
    container_name: passmgr
    restart: always
    command: /start
    ports:
      - 7001:7000
    volumes:
      - .:/code

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/static
    restart: always
    ports:
      - 81:81
    depends_on:
      - web

volumes:
  static_volume: