# Generated by Django 3.0.4 on 2020-04-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0002_auto_20200414_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordaccount',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
