# Generated by Django 3.0.4 on 2020-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0003_auto_20200414_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('idsession', models.AutoField(primary_key=True, serialize=False)),
                ('current_signed_in_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idnew_table', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('savedtheme', models.CharField(blank=True, max_length=45, null=True)),
                ('isadmin', models.CharField(blank=True, max_length=45, null=True)),
                ('isdisabled', models.CharField(blank=True, max_length=45, null=True)),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='passwordaccount',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='passwordaccount',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='passwordaccount',
            name='creation_date',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='passwordaccount',
            name='last_modified',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
