# Generated by Django 3.0.4 on 2020-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0004_auto_20200414_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordaccount',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.AlterField(
            model_name='passwordaccount',
            name='additional_notes',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='passwordaccount',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordaccount',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
