# Generated by Django 3.0.4 on 2020-04-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0005_auto_20200414_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
