# Generated by Django 3.0.4 on 2020-04-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0006_auto_20200414_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordaccount',
            old_name='creator_id',
            new_name='user',
        ),
    ]
