# Generated by Django 3.0.5 on 2020-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0007_auto_20200416_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordaccount',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=45),
        ),
    ]
