# Generated by Django 3.0.5 on 2020-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0010_auto_20200418_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordaccount',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
