# Generated by Django 3.2.12 on 2022-04-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmjrapp', '0011_auto_20200508_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordaccount',
            name='otp',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='passwordaccount',
            name='pin',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='passwordaccount',
            name='rim',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='passwordaccount',
            name='subscription_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='passwordaccount',
            name='username_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
